language: python
python:
  - "3.5"
script: true
install: "pip install mkdocs"
after_success:
  - if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then ./.deploy.sh ; fi
env:
  global:
    - SITE_URL: https://o2r-project.github.io/o2r-web-api
    - GH_USER_NAME: "Jan Koppe"
    - GH_USER_EMAIL: jan.koppe@wwu.de
    - GH_REF: github.com/o2r-project/o2r-web-api
    - secure: "JWIwvx1Cphz4WFYiVJebXvC7N57GlRrThlq/dnR82RNQHKbXKxm/OeCPL5zHJ+olkr/8v1l+YxdRCt/i6ZdgG1H7iWCPfiCcrAP3nxROWH5vOzLt0mz2o2JPnHAVJxOC0kn3iQG0OeUSuK6NHs3b487hwbdecVLsYarduOwJ6gam83P/IK9gFfWL0nqJ6TUrTNj4olrmj92Nw4C38WrWvB4Q9QPCbBW4gxMZlGTPvF12mHktoBQzqtLQQPbrDQHiaGcWajQP/tefpLa5SitxHDZHh5lXRaPkGEJ90rXSzQ1P8rxODgxFG5lMPYAJ6uJvKMbuRTKwI5MCvnJ5v1uBSJjvBQdOAkkbbLVg2AFYe50i3qDzFytt9K3rswHeKVKPSkkuzu7qOV+rHe8W6IzsM1HlNJ/cA2RVbDcl1O0UH5NHgZwboga8EAUkAqirA97sbkPjtq0eJ0AyFU561TvEaFHfqkjGz/FlbOE655kxXxZXJ74n0VtMwjYpW8i9kA4UkN5O/h7MRo+mbEWeWUvRhISPXDUEClkpwS+ifqQQb65ORx5cmkkzylA7hD0mqTxtT9U9yLQRZfjMmJIv3vhY1Nl3gcB+JpB5pnM0biH11SjJ28tbqPg2Pj2rAfI6tTCilyEcNOSEP+Z2rNRObwkhGIes0ZTlvAa2oycrrU9gIVI="

