language: python
script: true
install:
  - pip install mkdocs
  - mkdocs --version
after_success:
  - if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then ./.deploy.sh ; fi
env:
  global:
    - SITE_URL: https://o2r.info/api
    - GH_USER_NAME: "Opening Reproducible Research"
    - GH_USER_EMAIL: openingrr@uni-muenster.de
    - GH_REF: github.com/o2r-project/api
    - secure: "WFw7tpMjdeMR3KE9eULaVifKCeiDN0oa6x6i6jhVM7DlEtiom6ZcE4SuUroHLZvzVktX2/HgTOiWlAgwyKtY7Ma+Aoy/hkrjPs+6n+n3DcxRt3bkpELvy7uM837Pqz0wd+WPjtKCk44jlWdDX8E6cMCHlaZFA3vD15vdDeXspe8myvYO1ubciDeu5gt6PG5MR2pbwCyHw10Pa36EjZbem2vC275yLUbJcB7umTSKtRQANKqb+52KmRgqFn1NF+gG1bWNPhX+T5bu4SW7jJOr1hKYxP6jkzjNXNOxOjTr9ha7jeE8Vd0wSdBlx1Sw94oUM1IOi6PnoPNNrIkEfHG/7g2k7kgFJWx8jPSvWwURA9x8jU3WhGbmaczUsI4UqCXJcV4Q9hMLd/VbRL200IjAXUXEA/c/o8HyAtkbhXMPsHSy+9HI3PrvvnTkI3S+6ggUFDCiAi8eQKw5QPIse0LgBxOo+NnH1r6KEV56eE40u2iGf4Jqx7HXu9xZWK/RjYwvVGnL1nYw5qV+nfzvW6GwzuVNb4DiHl9FQSxblCD/IDmyZ8Afe5RlzeZWDuFlSzFRvggAoMkOLhBfu9sRLA5J2bBTjpVYz6FM+sJfYd5u+xkGI7fs62dQqjM+eSZDIZmdATrf/q+cf0aYdpI93S7rnqPFYdX28EucuhHfNAyZLx8="
