site_name: o2r web API
pages:
  - Index:      index.md
  - Upload:     upload.md
  - Job:        job.md
  - Compendium: compendium.md
  - User:       user.md
  - Search:     search.md
theme: readthedocs # flatly, cinder
site_dir: docs/html
extra_css: [o2r.css]