site_name: o2r web API
pages:
  - Home: index.md
  - Compendium:
    - Create new compendium:
      - API upload: compendium/upload.md
      - Public share submission: compendium/public_share.md
    - View: compendium/view.md
    - Download: compendium/download.md
    - Metadata: compendium/metadata.md
    - Files in a compendium: compendium/files.md
  - Job: job.md
  - Search: search.md
  - Shipment: shipment.md
  - User: user.md
theme: readthedocs # flatly, cinder
site_dir: site
extra_css: [o2r.css]
