site_name: o2r web API
site_author: "Daniel Nüst, Marc Schutzeichel, Markus Konkol"
site_description: "Executable Research Compendium technical specification, user guides, developer guides, and support."
copyright: "Licensed under Creative Commons CC0 1.0 Universal License."
nav:
  - Home: index.md
  - Compendium:
    - Create new compendium:
      - API upload: compendium/upload.md
      - Public share submission: compendium/public_share.md
      - Candidates: compendium/candidate.md
    - View: compendium/view.md
    - Delete: compendium/delete.md
    - Download: compendium/download.md
    - Metadata: compendium/metadata.md
    - Files in a compendium: compendium/files.md
    - Substitution: compendium/substitute.md
    - Public links: compendium/link.md
  - Job: job.md
  - Search: search.md
  - Shipment: shipment.md
  - User: user.md
theme:
    name: readthedocs
    custom_dir: custom_theme
repo_url: https://github.com/o2r-project/api
repo_name: GitHub
edit_uri: tree/master/docs/
site_url: https://o2r.info/api/
site_dir: site
extra_css: [o2r.css]
markdown_extensions:
  - markdown.extensions.admonition
  - toc:
      permalink: true