
name: PDF generation

on:
  push:
    branches:
    - master
  workflow_dispatch:

jobs: 
  pdf-generation:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout 
      uses: actions/checkout@v1
      with:
        check-latest: false
        node-version: 14.16.0
        token: ${{ secrets.TEST_PAT }}

    - name: Install node
      uses: actions/setup-node@v1

    - name: Install widdershins
      run: npm install -g widdershins

    - name: Install mdpdf
      run: npm install -g mdpdf@2.1.1 --unsafe-perm
    
    - name: Convert spec to md
      run: widdershins ./docs/o2r-openapi.yml -c false -o ./docs/o2r-openapi.md

    - name: Convert md to pdf
      run: mdpdf ./docs/o2r-openapi.md

    - name: Delete the md file
      run: rm ./docs/*.md

    - name: Commit the new PDF
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_author: PDF bot <o2r.projekt@uni-muenster.de>
        commit_message: update spec pdf
        commit_user_name: Fmazin
        commit_uset_email: fabian.fermazin@wwu.de
        branch: master
